apiVersion: apps/v1
kind: Deployment
metadata:
  name: persons-app-deployment
spec:
  selector:
    matchLabels:
      app: persons-app
  replicas: 1
  template:
    metadata:
      labels:
        app: persons-app
    spec:
      containers:
      - name: persons
        image: apovyshev/postgres:app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: persons-loadbalancer
  labels:
    app: persons-app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      name: http 
  selector:
    app: persons-app    