apiVersion: apps/v1
kind: Deployment
metadata:
  name: persons-app
spec:
  selector:
    matchLabels:
      app: persons-app
  replicas: 2
  template:
    metadata:
      labels:
        app: persons-app
    spec:
      containers:
      - name: persons-app
        image: apovyshev/postgres:app
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: persons-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: persons-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http  
